# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GORM
subtitle: The fantastic ORM library for Golang, aims to be developer friendly.
description: GORM is a fantastic ORM library for Golang, aims to be developer friendly.
author: Jinzhu
author_url: https://github.com/jinzhu
language: en
timezone: UTC
source_dir: pages
skip_render: [driver/**, plugin/**, datatypes.html, gorm.html, hints.html, gen.html, sharding.html, gormx.html]

# URL
url: https://gorm.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Start Guide
start: "go get -u gorm.io/gorm"

# Common Configuration
twitter: zhangjinzhu
github: go-gorm/gorm
disqus_shortname: gormv2
algolia:
  en:
    api_key: 442683d88a109de42c6d01bb0c7c4cec
    index_name: gorm
google_tag_manager: GTM-WSNPD75

# Writing
new_post_name: :title.md # File name of new posts
external_link:
  enable: true # Open external links in new tab
filename_case: 0
relative_link: false
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: '  '

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: navy  # based from hexo offical site
