# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GORM
subtitle: The fantastic ORM library for Golang, aims to be developer friendly.
description: GORM is a fantastic ORM library for Golang, aims to be developer friendly.
author: Jinzhu
author_url: https://github.com/jinzhu
language: en
timezone: UTC
source_dir: pages
skip_render: [driver/**, plugin/**, datatypes.html, gorm.html, hints.html]

# URL
url: http://gorm.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Start Guide
start: "go get -u github.com/jinzhu/gorm"

# Common Configuration
twitter: zhangjinzhu
github: go-gorm/gorm
disqus_shortname: gorm
algolia:
  en:
    api_key: 442683d88a109de42c6d01bb0c7c4cec
    index_name: gorm
google_tag_manager: GTM-WSNPD75

# Writing
new_post_name: :title.md # File name of new posts
external_link: true # Open external links in new tab
filename_case: 0
relative_link: false
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '  '

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: navy  # based from hexo offical site

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://__GITHUB_TOKEN__@github.com/go-gorm/gorm.io.git
  branch: gh-pages
