name: hexo

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: solybum/hexo-deploy@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REPOSITORY: go-gorm/gorm.io # The repository the action should deploy to.
          BRANCH: gh-pages  # The branch the action should deploy to.
          PUBLISH_DIR: ./public # The folder the action should deploy.
